### ISSUE TITLE
[Error]: Invalid status code: 1 

### ISSUE THREAD

**Issue by Anirudh-A-V** [Readme-Workflows/recent-activity#226]
This is the error message I am getting...

```
serializers
{
  PushEvent: [Function: PushEvent],
  IssuesEvent: [Function: IssuesEvent],
  PullRequestEvent: [Function: PullRequestEvent],
  CreateEvent: [Function: CreateEvent],
  ForkEvent: [Function: ForkEvent],
  GollumEvent: [Function: GollumEvent],
  MemberEvent: [Function: MemberEvent],
  PullRequestReviewEvent: [Function: PullRequestReviewEvent],
  ReleaseEvent: [Function: ReleaseEvent],
  WatchEvent: [Function: WatchEvent]
}
⬤  debug     Getting activity for Anirudh-A-V
⬤  debug     100 events found for Anirudh-A-V.
[
  '⬆️ Pushed 1 commit(s) to [Anirudh-A-V/Anirudh-A-V](https://github.com/Anirudh-A-V/Anirudh-A-V)',
  '⬆️ Pushed 1 commit(s) to [Anirudh-A-V/Anirudh-A-V](https://github.com/Anirudh-A-V/Anirudh-A-V)',
  '🔱 Forked [Anirudh-A-V/recent-activity](https://github.com/Anirudh-A-V/recent-activity) from [Readme-Workflows/recent-activity](https://github.com/Readme-Workflows/recent-activity)',
  '⬆️ Pushed 1 commit(s) to [Anirudh-A-V/Anirudh-A-V](https://github.com/Anirudh-A-V/Anirudh-A-V)',
  '⬆️ Pushed 1 commit(s) to [Anirudh-A-V/Anirudh-A-V](https://github.com/Anirudh-A-V/Anirudh-A-V)'
]

{ hello: 'readme-workflows.glitch.me' }
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 1 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Readme-Workflows/recent-activity/v2.4.0/dist/index.js:32326:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
```
I have tried :
> Re-running the workflow
> Deleting the previous yml file and adding a new one.

It seems that the pipeline is broken or maybe I am doing something wrong...

**Comment by abhijoshi2k** [comment]
Try comparing your setup with my readme repo.

**Comment by abhijoshi2k** [comment]
Closing issue.
Reason: No response.
