### ISSUE TITLE
Bug report: Error: Invalid status code: 1 

### ISSUE THREAD

**Issue by bloedboemmel** [Readme-Workflows/recent-activity#84]
When Running recent-activity@v2.3.0, I always get:
```
⬤  debug     Getting activity for bloedboemmel
⬤  debug     31 events found for bloedboemmel.
[
  '⭐ Starred [bloedboemmel/Steinbock](https://github.com/bloedboemmel/Steinbock)',
  '⭐ Starred [eth-cscs/SummerSchool2021](https://github.com/eth-cscs/SummerSchool2021)',
  '🔱 Forked [bloedboemmel/novatorem](https://github.com/bloedboemmel/novatorem) from [novatorem/novatorem](https://github.com/novatorem/novatorem)',
  '⭐ Starred [Festify/app](https://github.com/Festify/app)',
  '📔 Created new repository [bloedboemmel/bloedboemmel](https://github.com/bloedboemmel/bloedboemmel)'
]
✔  success   Updated README with the recent activity
{ hello: 'readme-workflows.glitch.me' }
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 1 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Readme-Workflows/recent-activity/v2.3.0/dist/index.js:24711:15)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)

```

So apparently getting the updates works. But after that something goes completly wrong. Any help appreciated!

**Comment by bloedboemmel** [comment]
It strangely worked again after making a new yml-Script

**Comment by abhijoshi2k** [comment]
Hello @bloedboemmel 
I've observed similar failures happen. However, it's very rare (once a week) scenario. But I just noticed that these errors occurred a lot of times in your case. Sorry for the inconvenience caused.
We'll try logging the error details when we release next so that we too will understand it better.
Thanks for bringing this to our notice 😊.
